/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.ControladorRegistro;

/**
 *
 * @author SOFIA ELIZONDO
 */
public class Botones extends javax.swing.JPanel {
    ControladorRegistro controlador;

    /**
     * Creates new form Botones
     */
    public Botones() {
        initComponents();
    }
    
    public void agregarEventos(ControladorRegistro controlador)
    {
        this.controlador=controlador;
        this.jbt_Buscar.addActionListener(controlador);
        this.jbt_Agregar.addActionListener(controlador);
        this.jbt_Modificar.addActionListener(controlador);
        this.jbt_Eliminar.addActionListener(controlador);
    }
    
    public void habilitarAgregar()
    {
        this.jbt_Agregar.setEnabled(true);
        this.jbt_Buscar.setEnabled(true);
        this.jbt_Eliminar.setEnabled(false);
        this.jbt_Modificar.setEnabled(false);
    }
    
    public void habilitarModificar()
    {
        this.jbt_Agregar.setEnabled(true);
        this.jbt_Buscar.setEnabled(true);
        this.jbt_Eliminar.setEnabled(true);
        this.jbt_Modificar.setEnabled(true);
    }
    
    
    public void estadoInicial()
    {
        this.jbt_Agregar.setEnabled(false);
        this.jbt_Buscar.setEnabled(true);
        this.jbt_Eliminar.setEnabled(false);
        this.jbt_Modificar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbt_Buscar = new javax.swing.JButton();
        jbt_Agregar = new javax.swing.JButton();
        jbt_Modificar = new javax.swing.JButton();
        jbt_Eliminar = new javax.swing.JButton();

        setOpaque(false);

        jbt_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Buscar.png"))); // NOI18N
        jbt_Buscar.setActionCommand("Buscar");
        jbt_Buscar.setBorderPainted(false);
        jbt_Buscar.setContentAreaFilled(false);
        jbt_Buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbt_Buscar.setFocusPainted(false);
        jbt_Buscar.setFocusable(false);

        jbt_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/agregar.png"))); // NOI18N
        jbt_Agregar.setActionCommand("Agregar");
        jbt_Agregar.setBorderPainted(false);
        jbt_Agregar.setContentAreaFilled(false);

        jbt_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Modificar.png"))); // NOI18N
        jbt_Modificar.setActionCommand("Modificar");
        jbt_Modificar.setBorderPainted(false);
        jbt_Modificar.setContentAreaFilled(false);

        jbt_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Borrar.png"))); // NOI18N
        jbt_Eliminar.setActionCommand("Eliminar");
        jbt_Eliminar.setBorderPainted(false);
        jbt_Eliminar.setContentAreaFilled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbt_Buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_Agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_Modificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_Eliminar)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbt_Eliminar)
                    .addComponent(jbt_Agregar)
                    .addComponent(jbt_Buscar)
                    .addComponent(jbt_Modificar))
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbt_Agregar;
    private javax.swing.JButton jbt_Buscar;
    private javax.swing.JButton jbt_Eliminar;
    private javax.swing.JButton jbt_Modificar;
    // End of variables declaration//GEN-END:variables
}
